M48
; DRILL file {KiCad 9.0.5} date 2025-10-24T14:38:57-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-24T14:38:57-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,8,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.450
%
G90
G05
T1
X104.52Y-117.605
X125.37Y-117.605
T2
X105.32Y-86.45
X123.88Y-84.2
M30
